// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
    GetEduV1AcademicYearData,
    GetEduV1AcademicYearResponses,
    PostEduV1AcademicYearData,
    PostEduV1AcademicYearResponses,
    GetEduV1AcademicYearGetItemsData,
    GetEduV1AcademicYearGetItemsResponses,
    DeleteEduV1AcademicYearByIdData,
    DeleteEduV1AcademicYearByIdResponses,
    GetEduV1AcademicYearByIdData,
    GetEduV1AcademicYearByIdResponses,
    PutEduV1AcademicYearByIdData,
    PutEduV1AcademicYearByIdResponses,
    GetEduV1AcademicYearGetCurrentData,
    GetEduV1AcademicYearGetCurrentResponses,
    PostEduV1AcademicYearSetCurrentByIdData,
    PostEduV1AcademicYearSetCurrentByIdResponses,
    GetEduV1ActionData,
    GetEduV1ActionResponses,
    PostEduV1ActionData,
    PostEduV1ActionResponses,
    GetEduV1ActionGetItemsData,
    GetEduV1ActionGetItemsResponses,
    DeleteEduV1ActionByIdData,
    DeleteEduV1ActionByIdResponses,
    GetEduV1ActionByIdData,
    GetEduV1ActionByIdResponses,
    PutEduV1ActionByIdData,
    PutEduV1ActionByIdResponses,
    GetEduV1CategoryCategoryItemsData,
    GetEduV1CategoryCategoryItemsResponses,
    GetEduV1CategoryData,
    GetEduV1CategoryResponses,
    PostEduV1CategoryData,
    PostEduV1CategoryResponses,
    DeleteEduV1CategoryByIdData,
    DeleteEduV1CategoryByIdResponses,
    GetEduV1CategoryByIdData,
    GetEduV1CategoryByIdResponses,
    PutEduV1CategoryByIdData,
    PutEduV1CategoryByIdResponses,
    GetEduV1CategoryItemCategoryCodeData,
    GetEduV1CategoryItemCategoryCodeResponses,
    GetEduV1CategoryItemCategoryCodeByCodeData,
    GetEduV1CategoryItemCategoryCodeByCodeResponses,
    GetEduV1CategoryItemGenderData,
    GetEduV1CategoryItemGenderResponses,
    GetEduV1CategoryItemData,
    GetEduV1CategoryItemResponses,
    PostEduV1CategoryItemData,
    PostEduV1CategoryItemResponses,
    DeleteEduV1CategoryItemByIdData,
    DeleteEduV1CategoryItemByIdResponses,
    GetEduV1CategoryItemByIdData,
    GetEduV1CategoryItemByIdResponses,
    PutEduV1CategoryItemByIdData,
    PutEduV1CategoryItemByIdResponses,
    GetEduV1CategoryItemGetByCategoryCodeAndCodeData,
    GetEduV1CategoryItemGetByCategoryCodeAndCodeResponses,
    GetEduV1CategoryItemGetCategoryItemByCategoryIdData,
    GetEduV1CategoryItemGetCategoryItemByCategoryIdResponses,
    GetEduV1CategoryItemGetCategoryItemByCategoryParentCodeData,
    GetEduV1CategoryItemGetCategoryItemByCategoryParentCodeResponses,
    GetEduV1DistrictProvinceByIdData,
    GetEduV1DistrictProvinceByIdResponses,
    GetEduV1DistrictByIdData,
    GetEduV1DistrictByIdResponses,
    GetEduV1ExtInfoSettingData,
    GetEduV1ExtInfoSettingResponses,
    PostEduV1ExtInfoSettingData,
    PostEduV1ExtInfoSettingResponses,
    DeleteEduV1ExtInfoSettingByIdData,
    DeleteEduV1ExtInfoSettingByIdResponses,
    GetEduV1ExtInfoSettingByIdData,
    GetEduV1ExtInfoSettingByIdResponses,
    PutEduV1ExtInfoSettingByIdData,
    PutEduV1ExtInfoSettingByIdResponses,
    GetEduV1MenuData,
    GetEduV1MenuResponses,
    PostEduV1MenuData,
    PostEduV1MenuResponses,
    GetEduV1MenuTreeData,
    GetEduV1MenuTreeResponses,
    GetEduV1MenuMenuUserData,
    GetEduV1MenuMenuUserResponses,
    GetEduV1MenuMenuItemsData,
    GetEduV1MenuMenuItemsResponses,
    DeleteEduV1MenuByIdData,
    DeleteEduV1MenuByIdResponses,
    GetEduV1MenuByIdData,
    GetEduV1MenuByIdResponses,
    PutEduV1MenuByIdData,
    PutEduV1MenuByIdResponses,
    GetEduV1MenuPermissionGetByMenuByMenuIdData,
    GetEduV1MenuPermissionGetByMenuByMenuIdResponses,
    PostEduV1MenuPermissionSetPermissionByMenuIdData,
    PostEduV1MenuPermissionSetPermissionByMenuIdResponses,
    GetEduV1OrganizationData,
    GetEduV1OrganizationResponses,
    PostEduV1OrganizationData,
    PostEduV1OrganizationResponses,
    GetEduV1OrganizationTreeData,
    GetEduV1OrganizationTreeResponses,
    DeleteEduV1OrganizationByIdData,
    DeleteEduV1OrganizationByIdResponses,
    GetEduV1OrganizationByIdData,
    GetEduV1OrganizationByIdResponses,
    PutEduV1OrganizationByIdData,
    PutEduV1OrganizationByIdResponses,
    GetEduV1OrganizationOrganizationItemData,
    GetEduV1OrganizationOrganizationItemResponses,
    GetEduV1OrganizationGetItemsData,
    GetEduV1OrganizationGetItemsResponses,
    GetEduV1OrganizationUserOrganizationsByOrganizationIdData,
    GetEduV1OrganizationUserOrganizationsByOrganizationIdResponses,
    DeleteEduV1OrganizationUserByIdData,
    DeleteEduV1OrganizationUserByIdResponses,
    GetEduV1OrganizationUserByIdData,
    GetEduV1OrganizationUserByIdResponses,
    PostEduV1OrganizationUserOrganizationsByOrganizationIdUsersData,
    PostEduV1OrganizationUserOrganizationsByOrganizationIdUsersResponses,
    GetEduV1PartnerData,
    GetEduV1PartnerResponses,
    PostEduV1PartnerData,
    PostEduV1PartnerResponses,
    DeleteEduV1PartnerByIdData,
    DeleteEduV1PartnerByIdResponses,
    GetEduV1PartnerByIdData,
    GetEduV1PartnerByIdResponses,
    PutEduV1PartnerByIdData,
    PutEduV1PartnerByIdResponses,
    GetEduV1PartnerGetItemsData,
    GetEduV1PartnerGetItemsResponses,
    GetEduV1PartnerGenerateAccessKeyByIdData,
    GetEduV1PartnerGenerateAccessKeyByIdResponses,
    GetEduV1PartnerKeyData,
    GetEduV1PartnerKeyResponses,
    PostEduV1PartnerKeyData,
    PostEduV1PartnerKeyResponses,
    DeleteEduV1PartnerKeyByIdData,
    DeleteEduV1PartnerKeyByIdResponses,
    GetEduV1PartnerKeyByIdData,
    GetEduV1PartnerKeyByIdResponses,
    PutEduV1PartnerKeyByIdData,
    PutEduV1PartnerKeyByIdResponses,
    GetEduV1PermissionData,
    GetEduV1PermissionResponses,
    PostEduV1PermissionData,
    PostEduV1PermissionResponses,
    DeleteEduV1PermissionByIdData,
    DeleteEduV1PermissionByIdResponses,
    GetEduV1PermissionByIdData,
    GetEduV1PermissionByIdResponses,
    PutEduV1PermissionByIdData,
    PutEduV1PermissionByIdResponses,
    PostEduV1PersonData,
    PostEduV1PersonResponses,
    DeleteEduV1PersonByIdData,
    DeleteEduV1PersonByIdResponses,
    PutEduV1PersonByIdData,
    PutEduV1PersonByIdResponses,
    PostEduV1PersonProfileData,
    PostEduV1PersonProfileResponses,
    DeleteEduV1PersonProfileByIdData,
    DeleteEduV1PersonProfileByIdResponses,
    PutEduV1PersonProfileByIdData,
    PutEduV1PersonProfileByIdResponses,
    GetEduV1ProfileData,
    GetEduV1ProfileResponses,
    PutEduV1ProfileData,
    PutEduV1ProfileResponses,
    PostEduV1ProfileChangePasswordData,
    PostEduV1ProfileChangePasswordResponses,
    GetEduV1ProvinceData,
    GetEduV1ProvinceResponses,
    GetEduV1RoleData,
    GetEduV1RoleResponses,
    PostEduV1RoleData,
    PostEduV1RoleResponses,
    DeleteEduV1RoleByIdData,
    DeleteEduV1RoleByIdResponses,
    GetEduV1RoleByIdData,
    GetEduV1RoleByIdResponses,
    PutEduV1RoleByIdData,
    PutEduV1RoleByIdResponses,
    GetEduV1RolePermissionData,
    GetEduV1RolePermissionResponses,
    PostEduV1RolePermissionSetData,
    PostEduV1RolePermissionSetResponses,
    GetEduV1SemesterGetByAcademicYearByAcademicYearIdData,
    GetEduV1SemesterGetByAcademicYearByAcademicYearIdResponses,
    GetEduV1SemesterGetItemsData,
    GetEduV1SemesterGetItemsResponses,
    PostEduV1SemesterData,
    PostEduV1SemesterResponses,
    DeleteEduV1SemesterByIdData,
    DeleteEduV1SemesterByIdResponses,
    GetEduV1SemesterByIdData,
    GetEduV1SemesterByIdResponses,
    PutEduV1SemesterByIdData,
    PutEduV1SemesterByIdResponses,
    GetEduV1SemesterGetCurrentData,
    GetEduV1SemesterGetCurrentResponses,
    PostEduV1SemesterSetCurrentByIdData,
    PostEduV1SemesterSetCurrentByIdResponses,
    GetEduV1UserData,
    GetEduV1UserResponses,
    PostEduV1UserData,
    PostEduV1UserResponses,
    GetEduV1UserGetItemsData,
    GetEduV1UserGetItemsResponses,
    GetEduV1UserFindOneData,
    GetEduV1UserFindOneResponses,
    DeleteEduV1UserByIdData,
    DeleteEduV1UserByIdResponses,
    GetEduV1UserByIdData,
    GetEduV1UserByIdResponses,
    PutEduV1UserByIdData,
    PutEduV1UserByIdResponses,
    PostEduV1AuthUserCheckMembershipData,
    PostEduV1AuthUserCheckMembershipResponses,
    PostEduV1AuthUserNewMembershipData,
    PostEduV1AuthUserNewMembershipResponses,
    PostEduV1AuthUserTokenData,
    PostEduV1AuthUserTokenResponses,
    PostEduV1AuthUserRefreshTokenData,
    PostEduV1AuthUserRefreshTokenResponses,
    PostEduV1AuthUserLogoutData,
    PostEduV1AuthUserLogoutResponses,
    GetEduV1UserDeviceData,
    GetEduV1UserDeviceResponses,
    GetEduV1UserMembershipData,
    GetEduV1UserMembershipResponses,
    PostEduV1UserMembershipData,
    PostEduV1UserMembershipResponses,
    PatchEduV1UserMembershipLockByIdData,
    PatchEduV1UserMembershipLockByIdResponses,
    PatchEduV1UserMembershipUnlockByIdData,
    PatchEduV1UserMembershipUnlockByIdResponses,
    GetEduV1UserMembershipGetProfileUserMembershipsData,
    GetEduV1UserMembershipGetProfileUserMembershipsResponses,
    GetEduV1UserRoleGetByRoleByRoleIdData,
    GetEduV1UserRoleGetByRoleByRoleIdResponses,
    GetEduV1UserRoleGetByUserByUserIdData,
    GetEduV1UserRoleGetByUserByUserIdResponses,
    PostEduV1UserRoleUsersByUserIdRolesData,
    PostEduV1UserRoleUsersByUserIdRolesResponses,
    PostEduV1UserRoleRolesByRoleIdUsersData,
    PostEduV1UserRoleRolesByRoleIdUsersResponses,
    DeleteEduV1UserRoleByIdData,
    DeleteEduV1UserRoleByIdResponses,
    GetEduV1WardDistrictByIdData,
    GetEduV1WardDistrictByIdResponses,
    GetEduV1WardByIdData,
    GetEduV1WardByIdResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getEduV1AcademicYear = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1AcademicYearData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1AcademicYearResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/AcademicYear",
        ...options,
    });
};

export const postEduV1AcademicYear = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1AcademicYearData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1AcademicYearResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/AcademicYear",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const getEduV1AcademicYearGetItems = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetEduV1AcademicYearGetItemsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1AcademicYearGetItemsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/AcademicYear/get-items",
        ...options,
    });
};

export const deleteEduV1AcademicYearById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteEduV1AcademicYearByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1AcademicYearByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/AcademicYear/{id}",
        ...options,
    });
};

export const getEduV1AcademicYearById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1AcademicYearByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1AcademicYearByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/AcademicYear/{id}",
        ...options,
    });
};

export const putEduV1AcademicYearById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1AcademicYearByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1AcademicYearByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/AcademicYear/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1AcademicYearGetCurrent = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetEduV1AcademicYearGetCurrentData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1AcademicYearGetCurrentResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/AcademicYear/get-current",
        ...options,
    });
};

export const postEduV1AcademicYearSetCurrentById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostEduV1AcademicYearSetCurrentByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).post<
        PostEduV1AcademicYearSetCurrentByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/AcademicYear/set-current/{id}",
        ...options,
    });
};

export const getEduV1Action = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1ActionData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1ActionResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Action",
        ...options,
    });
};

export const postEduV1Action = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1ActionData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1ActionResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Action",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const getEduV1ActionGetItems = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1ActionGetItemsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1ActionGetItemsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Action/get-items",
        ...options,
    });
};

export const deleteEduV1ActionById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1ActionByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1ActionByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Action/{id}",
        ...options,
    });
};

export const getEduV1ActionById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1ActionByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1ActionByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Action/{id}",
        ...options,
    });
};

export const putEduV1ActionById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1ActionByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1ActionByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Action/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1CategoryCategoryItems = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetEduV1CategoryCategoryItemsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1CategoryCategoryItemsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Category/category-items",
        ...options,
    });
};

export const getEduV1Category = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1CategoryData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1CategoryResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Category",
        ...options,
    });
};

export const postEduV1Category = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1CategoryData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1CategoryResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Category",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1CategoryById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1CategoryByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1CategoryByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Category/{id}",
        ...options,
    });
};

export const getEduV1CategoryById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1CategoryByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1CategoryByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Category/{id}",
        ...options,
    });
};

export const putEduV1CategoryById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1CategoryByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1CategoryByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Category/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1CategoryItemCategoryCode = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetEduV1CategoryItemCategoryCodeData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1CategoryItemCategoryCodeResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem/category-code",
        ...options,
    });
};

export const getEduV1CategoryItemCategoryCodeByCode = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetEduV1CategoryItemCategoryCodeByCodeData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1CategoryItemCategoryCodeByCodeResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem/category-code/{code}",
        ...options,
    });
};

export const getEduV1CategoryItemGender = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetEduV1CategoryItemGenderData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1CategoryItemGenderResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem/gender",
        ...options,
    });
};

export const getEduV1CategoryItem = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1CategoryItemData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1CategoryItemResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem",
        ...options,
    });
};

export const postEduV1CategoryItem = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1CategoryItemData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1CategoryItemResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1CategoryItemById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteEduV1CategoryItemByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1CategoryItemByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem/{id}",
        ...options,
    });
};

export const getEduV1CategoryItemById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1CategoryItemByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1CategoryItemByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem/{id}",
        ...options,
    });
};

export const putEduV1CategoryItemById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1CategoryItemByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1CategoryItemByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1CategoryItemGetByCategoryCodeAndCode = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetEduV1CategoryItemGetByCategoryCodeAndCodeData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1CategoryItemGetByCategoryCodeAndCodeResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem/get-by-category-code-and-code",
        ...options,
    });
};

export const getEduV1CategoryItemGetCategoryItemByCategoryId = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetEduV1CategoryItemGetCategoryItemByCategoryIdData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1CategoryItemGetCategoryItemByCategoryIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem/get-category-item-by-category-id",
        ...options,
    });
};

export const getEduV1CategoryItemGetCategoryItemByCategoryParentCode = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetEduV1CategoryItemGetCategoryItemByCategoryParentCodeData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1CategoryItemGetCategoryItemByCategoryParentCodeResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/CategoryItem/get-category-item-by-category-parent-code",
        ...options,
    });
};

export const getEduV1DistrictProvinceById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetEduV1DistrictProvinceByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1DistrictProvinceByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/District/province/{id}",
        ...options,
    });
};

export const getEduV1DistrictById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1DistrictByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1DistrictByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/District/{id}",
        ...options,
    });
};

export const getEduV1ExtInfoSetting = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1ExtInfoSettingData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1ExtInfoSettingResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/ExtInfoSetting",
        ...options,
    });
};

export const postEduV1ExtInfoSetting = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1ExtInfoSettingData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1ExtInfoSettingResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/ExtInfoSetting",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1ExtInfoSettingById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteEduV1ExtInfoSettingByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1ExtInfoSettingByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/ExtInfoSetting/{id}",
        ...options,
    });
};

export const getEduV1ExtInfoSettingById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetEduV1ExtInfoSettingByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1ExtInfoSettingByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/ExtInfoSetting/{id}",
        ...options,
    });
};

export const putEduV1ExtInfoSettingById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PutEduV1ExtInfoSettingByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1ExtInfoSettingByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/ExtInfoSetting/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1Menu = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1MenuData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1MenuResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Menu",
        ...options,
    });
};

export const postEduV1Menu = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1MenuData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1MenuResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Menu",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const getEduV1MenuTree = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1MenuTreeData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1MenuTreeResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Menu/tree",
        ...options,
    });
};

export const getEduV1MenuMenuUser = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1MenuMenuUserData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1MenuMenuUserResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Menu/menu-user",
        ...options,
    });
};

export const getEduV1MenuMenuItems = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1MenuMenuItemsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1MenuMenuItemsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Menu/menu-items",
        ...options,
    });
};

export const deleteEduV1MenuById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1MenuByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1MenuByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Menu/{id}",
        ...options,
    });
};

export const getEduV1MenuById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1MenuByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1MenuByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Menu/{id}",
        ...options,
    });
};

export const putEduV1MenuById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1MenuByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1MenuByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Menu/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1MenuPermissionGetByMenuByMenuId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetEduV1MenuPermissionGetByMenuByMenuIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1MenuPermissionGetByMenuByMenuIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/MenuPermission/get-by-menu/{menuId}",
        ...options,
    });
};

export const postEduV1MenuPermissionSetPermissionByMenuId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        PostEduV1MenuPermissionSetPermissionByMenuIdData,
        ThrowOnError
    >,
) => {
    return (options.client ?? _heyApiClient).post<
        PostEduV1MenuPermissionSetPermissionByMenuIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/MenuPermission/set-permission/{menuId}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1Organization = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1OrganizationData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1OrganizationResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Organization",
        ...options,
    });
};

export const postEduV1Organization = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1OrganizationData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1OrganizationResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Organization",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const getEduV1OrganizationTree = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1OrganizationTreeData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1OrganizationTreeResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Organization/tree",
        ...options,
    });
};

export const deleteEduV1OrganizationById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteEduV1OrganizationByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1OrganizationByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Organization/{id}",
        ...options,
    });
};

export const getEduV1OrganizationById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1OrganizationByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1OrganizationByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Organization/{id}",
        ...options,
    });
};

export const putEduV1OrganizationById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1OrganizationByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1OrganizationByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Organization/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1OrganizationOrganizationItem = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetEduV1OrganizationOrganizationItemData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1OrganizationOrganizationItemResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Organization/organization-item",
        ...options,
    });
};

export const getEduV1OrganizationGetItems = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetEduV1OrganizationGetItemsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1OrganizationGetItemsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Organization/get-items",
        ...options,
    });
};

export const getEduV1OrganizationUserOrganizationsByOrganizationId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetEduV1OrganizationUserOrganizationsByOrganizationIdData,
        ThrowOnError
    >,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1OrganizationUserOrganizationsByOrganizationIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/OrganizationUser/organizations/{organizationId}",
        ...options,
    });
};

export const deleteEduV1OrganizationUserById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteEduV1OrganizationUserByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1OrganizationUserByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/OrganizationUser/{id}",
        ...options,
    });
};

export const getEduV1OrganizationUserById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetEduV1OrganizationUserByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1OrganizationUserByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/OrganizationUser/{id}",
        ...options,
    });
};

export const postEduV1OrganizationUserOrganizationsByOrganizationIdUsers = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        PostEduV1OrganizationUserOrganizationsByOrganizationIdUsersData,
        ThrowOnError
    >,
) => {
    return (options.client ?? _heyApiClient).post<
        PostEduV1OrganizationUserOrganizationsByOrganizationIdUsersResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/OrganizationUser/organizations/{organizationId}/users",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1Partner = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1PartnerData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1PartnerResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Partner",
        ...options,
    });
};

export const postEduV1Partner = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1PartnerData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1PartnerResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Partner",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1PartnerById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1PartnerByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1PartnerByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Partner/{id}",
        ...options,
    });
};

export const getEduV1PartnerById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1PartnerByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1PartnerByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Partner/{id}",
        ...options,
    });
};

export const putEduV1PartnerById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1PartnerByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1PartnerByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Partner/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1PartnerGetItems = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1PartnerGetItemsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1PartnerGetItemsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Partner/get-items",
        ...options,
    });
};

export const getEduV1PartnerGenerateAccessKeyById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetEduV1PartnerGenerateAccessKeyByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1PartnerGenerateAccessKeyByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Partner/generate-access-key/{id}",
        ...options,
    });
};

export const getEduV1PartnerKey = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1PartnerKeyData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1PartnerKeyResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/PartnerKey",
        ...options,
    });
};

export const postEduV1PartnerKey = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1PartnerKeyData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1PartnerKeyResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/PartnerKey",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1PartnerKeyById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1PartnerKeyByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1PartnerKeyByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/PartnerKey/{id}",
        ...options,
    });
};

export const getEduV1PartnerKeyById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1PartnerKeyByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1PartnerKeyByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/PartnerKey/{id}",
        ...options,
    });
};

export const putEduV1PartnerKeyById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1PartnerKeyByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1PartnerKeyByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/PartnerKey/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1Permission = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1PermissionData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1PermissionResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Permission",
        ...options,
    });
};

export const postEduV1Permission = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1PermissionData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1PermissionResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Permission",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1PermissionById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1PermissionByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1PermissionByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Permission/{id}",
        ...options,
    });
};

export const getEduV1PermissionById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1PermissionByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1PermissionByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Permission/{id}",
        ...options,
    });
};

export const putEduV1PermissionById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1PermissionByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1PermissionByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Permission/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const postEduV1Person = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1PersonData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1PersonResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Person",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1PersonById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1PersonByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1PersonByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Person/{id}",
        ...options,
    });
};

export const putEduV1PersonById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1PersonByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1PersonByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Person/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const postEduV1PersonProfile = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1PersonProfileData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1PersonProfileResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/PersonProfile",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1PersonProfileById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteEduV1PersonProfileByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1PersonProfileByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/PersonProfile/{id}",
        ...options,
    });
};

export const putEduV1PersonProfileById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1PersonProfileByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1PersonProfileByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/PersonProfile/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1Profile = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1ProfileData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1ProfileResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Profile",
        ...options,
    });
};

export const putEduV1Profile = <ThrowOnError extends boolean = false>(
    options?: Options<PutEduV1ProfileData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).put<
        PutEduV1ProfileResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Profile",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const postEduV1ProfileChangePassword = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<PostEduV1ProfileChangePasswordData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1ProfileChangePasswordResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Profile/change-password",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const getEduV1Province = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1ProvinceData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1ProvinceResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Province",
        ...options,
    });
};

export const getEduV1Role = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1RoleData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1RoleResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Role",
        ...options,
    });
};

export const postEduV1Role = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1RoleData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1RoleResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Role",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1RoleById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1RoleByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1RoleByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Role/{id}",
        ...options,
    });
};

export const getEduV1RoleById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1RoleByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1RoleByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Role/{id}",
        ...options,
    });
};

export const putEduV1RoleById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1RoleByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1RoleByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Role/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1RolePermission = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1RolePermissionData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1RolePermissionResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/RolePermission",
        ...options,
    });
};

export const postEduV1RolePermissionSet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<PostEduV1RolePermissionSetData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1RolePermissionSetResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/RolePermission/set",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const getEduV1SemesterGetByAcademicYearByAcademicYearId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetEduV1SemesterGetByAcademicYearByAcademicYearIdData,
        ThrowOnError
    >,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1SemesterGetByAcademicYearByAcademicYearIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Semester/get-by-academic-year/{academicYearId}",
        ...options,
    });
};

export const getEduV1SemesterGetItems = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1SemesterGetItemsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1SemesterGetItemsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Semester/get-items",
        ...options,
    });
};

export const postEduV1Semester = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1SemesterData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1SemesterResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Semester",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const deleteEduV1SemesterById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1SemesterByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1SemesterByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Semester/{id}",
        ...options,
    });
};

export const getEduV1SemesterById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1SemesterByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1SemesterByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Semester/{id}",
        ...options,
    });
};

export const putEduV1SemesterById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1SemesterByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1SemesterByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Semester/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const getEduV1SemesterGetCurrent = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetEduV1SemesterGetCurrentData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1SemesterGetCurrentResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Semester/get-current",
        ...options,
    });
};

export const postEduV1SemesterSetCurrentById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostEduV1SemesterSetCurrentByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).post<
        PostEduV1SemesterSetCurrentByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Semester/set-current/{id}",
        ...options,
    });
};

export const getEduV1User = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1UserData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1UserResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/User",
        ...options,
    });
};

export const postEduV1User = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1UserData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1UserResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/User",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const getEduV1UserGetItems = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1UserGetItemsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1UserGetItemsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/User/get-items",
        ...options,
    });
};

export const getEduV1UserFindOne = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1UserFindOneData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1UserFindOneResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/User/find-one",
        ...options,
    });
};

export const deleteEduV1UserById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1UserByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1UserByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/User/{id}",
        ...options,
    });
};

export const getEduV1UserById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1UserByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1UserByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/User/{id}",
        ...options,
    });
};

export const putEduV1UserById = <ThrowOnError extends boolean = false>(
    options: Options<PutEduV1UserByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).put<
        PutEduV1UserByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/User/{id}",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const postEduV1AuthUserCheckMembership = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<PostEduV1AuthUserCheckMembershipData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1AuthUserCheckMembershipResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/auth/User/check-membership",
        ...options,
    });
};

export const postEduV1AuthUserNewMembership = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<PostEduV1AuthUserNewMembershipData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1AuthUserNewMembershipResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/auth/User/new-membership",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const postEduV1AuthUserToken = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1AuthUserTokenData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1AuthUserTokenResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/auth/User/token",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const postEduV1AuthUserRefreshToken = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<PostEduV1AuthUserRefreshTokenData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1AuthUserRefreshTokenResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/auth/User/refresh-token",
        ...options,
    });
};

export const postEduV1AuthUserLogout = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1AuthUserLogoutData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1AuthUserLogoutResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/auth/User/logout",
        ...options,
    });
};

export const getEduV1UserDevice = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1UserDeviceData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1UserDeviceResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserDevice",
        ...options,
    });
};

export const getEduV1UserMembership = <ThrowOnError extends boolean = false>(
    options?: Options<GetEduV1UserMembershipData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1UserMembershipResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserMembership",
        ...options,
    });
};

export const postEduV1UserMembership = <ThrowOnError extends boolean = false>(
    options?: Options<PostEduV1UserMembershipData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        PostEduV1UserMembershipResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserMembership",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options?.headers,
        },
    });
};

export const patchEduV1UserMembershipLockById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PatchEduV1UserMembershipLockByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).patch<
        PatchEduV1UserMembershipLockByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserMembership/lock/{id}",
        ...options,
    });
};

export const patchEduV1UserMembershipUnlockById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PatchEduV1UserMembershipUnlockByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).patch<
        PatchEduV1UserMembershipUnlockByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserMembership/unlock/{id}",
        ...options,
    });
};

export const getEduV1UserMembershipGetProfileUserMemberships = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetEduV1UserMembershipGetProfileUserMembershipsData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetEduV1UserMembershipGetProfileUserMembershipsResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserMembership/get-profile-user-memberships",
        ...options,
    });
};

export const getEduV1UserRoleGetByRoleByRoleId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetEduV1UserRoleGetByRoleByRoleIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1UserRoleGetByRoleByRoleIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserRole/get-by-role/{roleId}",
        ...options,
    });
};

export const getEduV1UserRoleGetByUserByUserId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetEduV1UserRoleGetByUserByUserIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1UserRoleGetByUserByUserIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserRole/get-by-user/{userId}",
        ...options,
    });
};

export const postEduV1UserRoleUsersByUserIdRoles = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostEduV1UserRoleUsersByUserIdRolesData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).post<
        PostEduV1UserRoleUsersByUserIdRolesResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserRole/users/{userId}/roles",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const postEduV1UserRoleRolesByRoleIdUsers = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostEduV1UserRoleRolesByRoleIdUsersData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).post<
        PostEduV1UserRoleRolesByRoleIdUsersResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserRole/roles/{roleId}/users",
        ...options,
        headers: {
            "Content-Type": "application/json; ver=1",
            ...options.headers,
        },
    });
};

export const deleteEduV1UserRoleById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteEduV1UserRoleByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).delete<
        DeleteEduV1UserRoleByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/UserRole/{id}",
        ...options,
    });
};

export const getEduV1WardDistrictById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1WardDistrictByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1WardDistrictByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Ward/district/{id}",
        ...options,
    });
};

export const getEduV1WardById = <ThrowOnError extends boolean = false>(
    options: Options<GetEduV1WardByIdData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetEduV1WardByIdResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/edu/v1/Ward/{id}",
        ...options,
    });
};
