// This file is auto-generated by @hey-api/openapi-ts

export type AcademicYear = {
  id?: number;
  createdUserId?: number | null;
  modifiedUserId?: number | null;
  createdDate?: string | null;
  modifiedDate?: string | null;
  isDeleted?: boolean | null;
  name?: string | null;
  fromDate?: string | null;
  toDate?: string | null;
};

export type AcademicYearBaseResponse = {
  success?: boolean;
  message?: string | null;
  data?: AcademicYear;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  meta?: unknown;
};

export type AddCategoryCommand = {
  code?: string | null;
  name?: string | null;
  descriptions?: string | null;
  orderId?: number | null;
  parentCategoryId?: number | null;
};

export type AddCategoryItemCommand = {
  categoryId?: number;
  sysCode?: string | null;
  code?: string | null;
  name?: string | null;
  value?: string | null;
  image?: string | null;
  parentCategoryCode?: string | null;
  orderId?: number | null;
};

export type AddExtInfoSettingCommand = {
  moduleCode?: string | null;
  extInfoCode?: string | null;
  extInfoName?: string | null;
  editorTypeId?: number | null;
  schoolLevelId?: number | null;
  categoryCode?: string | null;
};

export type AddOrganizationCommand = {
  name?: string | null;
  typeId?: number | null;
  parentId?: number | null;
  code?: string | null;
  provinceId?: number | null;
  districtId?: number | null;
  wardId?: number | null;
  address?: string | null;
  regionId?: number | null;
  phone?: string | null;
  email?: string | null;
  fax?: string | null;
  website?: string | null;
  mapLocation?: string | null;
};

export type AddPersonCommand = {
  code?: string | null;
  identityNo?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  doB?: string | null;
  genderId?: number | null;
  faceUrl?: string | null;
  organizationId?: number | null;
};

export type AddPersonProfileCommand = {
  code?: string | null;
  identityNo?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  doB?: string | null;
  genderId?: number | null;
  faceUrl?: string | null;
  organizationId?: number | null;
  personId?: number | null;
};

export type AssignRoleToUserCommand = {
  roleId?: number;
};

export type AssignUserToOrganizationCommand = {
  userId?: number;
};

export type AssignUserToRoleCommand = {
  userId?: number;
};

export type BaseResponse = {
  success?: boolean;
  message?: string | null;
  data?: unknown;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  meta?: unknown;
};

export type ChangePasswordUserCommand = {
  oldPassword?: string | null;
  password?: string | null;
  confirmPassword?: string | null;
};

export type CreateAcademicYearCommand = {
  name?: string | null;
  fromDate?: string | null;
  toDate?: string | null;
};

export type CreateActionCommand = {
  name?: string | null;
  service?: string | null;
  area?: string | null;
  controller?: string | null;
  httpMethod?: string | null;
  version?: string | null;
  route?: string | null;
  description?: string | null;
  allowAnonymous?: boolean | null;
};

export type CreateMenuCommand = {
  resource?: string | null;
  name?: string | null;
  icon?: string | null;
  path?: string | null;
  parentId?: number | null;
  orderId?: number | null;
  isActive?: boolean | null;
  isTitle?: boolean | null;
};

export type CreatePartnerAccessKeyCommand = {
  partnerId?: number | null;
  schoolCode?: string | null;
  ipAddresses?: string | null;
  secretKey?: string | null;
};

export type CreatePartnerCommand = {
  code?: string | null;
  name?: string | null;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
};

export type CreatePermissionCommand = {
  name?: string | null;
  actionId?: number;
  resource?: string | null;
};

export type CreateRoleCommand = {
  code?: string | null;
  name?: string | null;
  description?: string | null;
};

export type CreateSemesterCommand = {
  code?: string | null;
  academicYearId?: number;
  name?: string | null;
  fromDate?: string | null;
  toDate?: string | null;
};

export type CreateUserCommand = {
  firstName?: string | null;
  lastName?: string | null;
  doB?: string | null;
  isActive?: boolean | null;
  provinceId?: number | null;
  districtId?: number | null;
  wardId?: number | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
};

export type CreateUserMembershipCommand = {
  userId?: number;
  client?: string | null;
  password?: string | null;
};

export type CurrentSemester = {
  id?: number;
  academicYearId?: number | null;
  code?: string | null;
  name?: string | null;
  fromDate?: string | null;
  toDate?: string | null;
};

export type CurrentSemesterBaseResponse = {
  success?: boolean;
  message?: string | null;
  data?: CurrentSemester;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  meta?: unknown;
};

export type District = {
  id?: number;
  createdUserId?: number | null;
  modifiedUserId?: number | null;
  createdDate?: string | null;
  modifiedDate?: string | null;
  isDeleted?: boolean | null;
  provinceId?: number;
  code?: string | null;
  name?: string | null;
  levelId?: number;
};

export type DistrictPaginatedResultReadable = {
  success?: boolean;
  message?: string | null;
  data?: Array<District> | null;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  currentPage?: number;
  readonly totalPages?: number;
  totalCount?: number;
  pageSize?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
};

export type DistrictPaginatedResultWritable = {
  success?: boolean;
  message?: string | null;
  data?: Array<District> | null;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  currentPage?: number;
  totalCount?: number;
  pageSize?: number;
};

export type EditActionCommand = {
  name?: string | null;
  service?: string | null;
  area?: string | null;
  controller?: string | null;
  httpMethod?: string | null;
  version?: string | null;
  route?: string | null;
  description?: string | null;
  allowAnonymous?: boolean | null;
};

export type EditMenuCommand = {
  resource?: string | null;
  name?: string | null;
  icon?: string | null;
  path?: string | null;
  parentId?: number | null;
  orderId?: number | null;
  isActive?: boolean | null;
  isTitle?: boolean | null;
};

export type EditPartnerAccessKeyCommand = {
  partnerId?: number | null;
  schoolCode?: string | null;
  ipAddresses?: string | null;
  secretKey?: string | null;
  endpointUrl?: string | null;
};

export type EditPartnerCommand = {
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  name?: string | null;
  code?: string | null;
};

export type EditPermissionCommand = {
  name?: string | null;
  actionId?: number;
  resource?: string | null;
};

export type EditRoleCommand = {
  name?: string | null;
  code?: string | null;
  description?: string | null;
};

export type EditUserCommand = {
  firstName?: string | null;
  lastName?: string | null;
  isActive?: boolean;
  provinceId?: number | null;
  districtId?: number | null;
  wardId?: number | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  doB?: string | null;
  photo?: string | null;
};

export type HttpStatusCode =
  | 100
  | 101
  | 102
  | 103
  | 200
  | 201
  | 202
  | 203
  | 204
  | 205
  | 206
  | 207
  | 208
  | 226
  | 300
  | 301
  | 302
  | 303
  | 304
  | 305
  | 306
  | 307
  | 308
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451
  | 500
  | 501
  | 502
  | 503
  | 504
  | 505
  | 506
  | 507
  | 508
  | 510
  | 511;

export type LoginUserCommand = {
  osType?: string | null;
  osVersion?: string | null;
  deviceName?: string | null;
  deviceId?: string | null;
  deviceModel?: string | null;
  username?: string | null;
  password?: string | null;
};

export type MenuPermissionItemCommand = {
  permissionId?: number;
  isSelected?: boolean;
};

export type NewUserMembershipCommand = {
  osType?: string | null;
  osVersion?: string | null;
  deviceName?: string | null;
  deviceId?: string | null;
  deviceModel?: string | null;
  userId: number;
  userName: string;
  key: string;
  password: string;
  confirmPassword: string;
};

export type PaginatedResultReadable = {
  success?: boolean;
  message?: string | null;
  data?: Array<unknown> | null;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  currentPage?: number;
  readonly totalPages?: number;
  totalCount?: number;
  pageSize?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
};

export type PaginatedResultWritable = {
  success?: boolean;
  message?: string | null;
  data?: Array<unknown> | null;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  currentPage?: number;
  totalCount?: number;
  pageSize?: number;
};

export type Province = {
  id?: number;
  createdUserId?: number | null;
  modifiedUserId?: number | null;
  createdDate?: string | null;
  modifiedDate?: string | null;
  isDeleted?: boolean | null;
  code?: string | null;
  name?: string | null;
  levelId?: number;
};

export type ProvincePaginatedResultReadable = {
  success?: boolean;
  message?: string | null;
  data?: Array<Province> | null;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  currentPage?: number;
  readonly totalPages?: number;
  totalCount?: number;
  pageSize?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
};

export type ProvincePaginatedResultWritable = {
  success?: boolean;
  message?: string | null;
  data?: Array<Province> | null;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  currentPage?: number;
  totalCount?: number;
  pageSize?: number;
};

export type Semester = {
  id?: number;
  createdUserId?: number | null;
  modifiedUserId?: number | null;
  createdDate?: string | null;
  modifiedDate?: string | null;
  isDeleted?: boolean | null;
  academicYearId?: number | null;
  code?: string | null;
  name?: string | null;
  fromDate?: string | null;
  toDate?: string | null;
};

export type SemesterBaseResponse = {
  success?: boolean;
  message?: string | null;
  data?: Semester;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  meta?: unknown;
};

export type SetRolePermissionCommand = {
  roleId?: number;
  permissionId?: number;
  isActive?: boolean;
};

export type UpdateAcademicYearCommand = {
  name?: string | null;
  fromDate?: string | null;
  toDate?: string | null;
};

export type UpdateCategoryCommand = {
  code?: string | null;
  name?: string | null;
  descriptions?: string | null;
  orderId?: number | null;
  parentCategoryId?: number | null;
};

export type UpdateCategoryItemCommand = {
  sysCode?: string | null;
  code?: string | null;
  name?: string | null;
  value?: string | null;
  image?: string | null;
  parentCategoryCode?: string | null;
  orderId?: number | null;
};

export type UpdateExtInfoSettingCommand = {
  moduleCode?: string | null;
  extInfoCode?: string | null;
  extInfoName?: string | null;
  editorTypeId?: number | null;
  schoolLevelId?: number | null;
  categoryCode?: string | null;
};

export type UpdateOrganizationCommand = {
  name?: string | null;
  typeId?: number | null;
  parentId?: number | null;
  code?: string | null;
  provinceId?: number | null;
  districtId?: number | null;
  wardId?: number | null;
  address?: string | null;
  regionId?: number | null;
  phone?: string | null;
  email?: string | null;
  fax?: string | null;
  website?: string | null;
  mapLocation?: string | null;
};

export type UpdatePersonCommand = {
  code?: string | null;
  identityNo?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  doB?: string | null;
  genderId?: number | null;
  faceUrl?: string | null;
  organizationId?: number | null;
  personId?: number | null;
};

export type UpdatePersonProfileCommand = {
  code?: string | null;
  identityNo?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  doB?: string | null;
  genderId?: number | null;
  faceUrl?: string | null;
  organizationId?: number | null;
  personId?: number | null;
};

export type UpdateSemesterCommand = {
  code?: string | null;
  name?: string | null;
  fromDate?: string | null;
  toDate?: string | null;
};

export type Ward = {
  id?: number;
  createdUserId?: number | null;
  modifiedUserId?: number | null;
  createdDate?: string | null;
  modifiedDate?: string | null;
  isDeleted?: boolean | null;
  districtId?: number;
  code?: string | null;
  name?: string | null;
  levelId?: number;
  district?: District;
};

export type WardPaginatedResultReadable = {
  success?: boolean;
  message?: string | null;
  data?: Array<Ward> | null;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  currentPage?: number;
  readonly totalPages?: number;
  totalCount?: number;
  pageSize?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
};

export type WardPaginatedResultWritable = {
  success?: boolean;
  message?: string | null;
  data?: Array<Ward> | null;
  showMessage?: boolean;
  statusCode?: HttpStatusCode;
  errors?: Array<string> | null;
  currentPage?: number;
  totalCount?: number;
  pageSize?: number;
};

export type GetEduV1AcademicYearData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/AcademicYear";
};

export type GetEduV1AcademicYearResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type GetEduV1AcademicYearResponse =
  GetEduV1AcademicYearResponses[keyof GetEduV1AcademicYearResponses];

export type PostEduV1AcademicYearData = {
  body?: CreateAcademicYearCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/AcademicYear";
};

export type PostEduV1AcademicYearResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type PostEduV1AcademicYearResponse =
  PostEduV1AcademicYearResponses[keyof PostEduV1AcademicYearResponses];

export type GetEduV1AcademicYearGetItemsData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/AcademicYear/get-items";
};

export type GetEduV1AcademicYearGetItemsResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type GetEduV1AcademicYearGetItemsResponse =
  GetEduV1AcademicYearGetItemsResponses[keyof GetEduV1AcademicYearGetItemsResponses];

export type DeleteEduV1AcademicYearByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/AcademicYear/{id}";
};

export type DeleteEduV1AcademicYearByIdResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type DeleteEduV1AcademicYearByIdResponse =
  DeleteEduV1AcademicYearByIdResponses[keyof DeleteEduV1AcademicYearByIdResponses];

export type GetEduV1AcademicYearByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/AcademicYear/{id}";
};

export type GetEduV1AcademicYearByIdResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type GetEduV1AcademicYearByIdResponse =
  GetEduV1AcademicYearByIdResponses[keyof GetEduV1AcademicYearByIdResponses];

export type PutEduV1AcademicYearByIdData = {
  body?: UpdateAcademicYearCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/AcademicYear/{id}";
};

export type PutEduV1AcademicYearByIdResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type PutEduV1AcademicYearByIdResponse =
  PutEduV1AcademicYearByIdResponses[keyof PutEduV1AcademicYearByIdResponses];

export type GetEduV1AcademicYearGetCurrentData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/AcademicYear/get-current";
};

export type GetEduV1AcademicYearGetCurrentResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type GetEduV1AcademicYearGetCurrentResponse =
  GetEduV1AcademicYearGetCurrentResponses[keyof GetEduV1AcademicYearGetCurrentResponses];

export type PostEduV1AcademicYearSetCurrentByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/AcademicYear/set-current/{id}";
};

export type PostEduV1AcademicYearSetCurrentByIdResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type PostEduV1AcademicYearSetCurrentByIdResponse =
  PostEduV1AcademicYearSetCurrentByIdResponses[keyof PostEduV1AcademicYearSetCurrentByIdResponses];

export type GetEduV1ActionData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
    pageNumber?: number;
    pageSize?: number;
  };
  url: "/edu/v1/Action";
};

export type GetEduV1ActionResponses = {
  /**
   * OK
   */
  200: PaginatedResultReadable;
};

export type GetEduV1ActionResponse =
  GetEduV1ActionResponses[keyof GetEduV1ActionResponses];

export type PostEduV1ActionData = {
  body?: CreateActionCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Action";
};

export type PostEduV1ActionResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1ActionResponse =
  PostEduV1ActionResponses[keyof PostEduV1ActionResponses];

export type GetEduV1ActionGetItemsData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
  };
  url: "/edu/v1/Action/get-items";
};

export type GetEduV1ActionGetItemsResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1ActionGetItemsResponse =
  GetEduV1ActionGetItemsResponses[keyof GetEduV1ActionGetItemsResponses];

export type DeleteEduV1ActionByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Action/{id}";
};

export type DeleteEduV1ActionByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type DeleteEduV1ActionByIdResponse =
  DeleteEduV1ActionByIdResponses[keyof DeleteEduV1ActionByIdResponses];

export type GetEduV1ActionByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Action/{id}";
};

export type GetEduV1ActionByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1ActionByIdResponse =
  GetEduV1ActionByIdResponses[keyof GetEduV1ActionByIdResponses];

export type PutEduV1ActionByIdData = {
  body?: EditActionCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Action/{id}";
};

export type PutEduV1ActionByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PutEduV1ActionByIdResponse =
  PutEduV1ActionByIdResponses[keyof PutEduV1ActionByIdResponses];

export type GetEduV1CategoryCategoryItemsData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Category/category-items";
};

export type GetEduV1CategoryCategoryItemsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
    pageSize?: number;
    pageNumber?: number;
  };
  url: "/edu/v1/Category";
};

export type GetEduV1CategoryResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1CategoryData = {
  body?: AddCategoryCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Category";
};

export type PostEduV1CategoryResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1CategoryByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Category/{id}";
};

export type DeleteEduV1CategoryByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Category/{id}";
};

export type GetEduV1CategoryByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutEduV1CategoryByIdData = {
  body?: UpdateCategoryCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Category/{id}";
};

export type PutEduV1CategoryByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryItemCategoryCodeData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/CategoryItem/category-code";
};

export type GetEduV1CategoryItemCategoryCodeResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryItemCategoryCodeByCodeData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    code: string;
  };
  query?: never;
  url: "/edu/v1/CategoryItem/category-code/{code}";
};

export type GetEduV1CategoryItemCategoryCodeByCodeResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryItemGenderData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/CategoryItem/gender";
};

export type GetEduV1CategoryItemGenderResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryItemData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    categoryId?: number;
    searchKey?: string;
    pageSize?: number;
    pageNumber?: number;
  };
  url: "/edu/v1/CategoryItem";
};

export type GetEduV1CategoryItemResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1CategoryItemData = {
  body?: AddCategoryItemCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/CategoryItem";
};

export type PostEduV1CategoryItemResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1CategoryItemByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/CategoryItem/{id}";
};

export type DeleteEduV1CategoryItemByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryItemByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/CategoryItem/{id}";
};

export type GetEduV1CategoryItemByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutEduV1CategoryItemByIdData = {
  body?: UpdateCategoryItemCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/CategoryItem/{id}";
};

export type PutEduV1CategoryItemByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryItemGetByCategoryCodeAndCodeData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    CategoryCode?: string;
    Code?: string;
  };
  url: "/edu/v1/CategoryItem/get-by-category-code-and-code";
};

export type GetEduV1CategoryItemGetByCategoryCodeAndCodeResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryItemGetCategoryItemByCategoryIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    id?: number;
  };
  url: "/edu/v1/CategoryItem/get-category-item-by-category-id";
};

export type GetEduV1CategoryItemGetCategoryItemByCategoryIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1CategoryItemGetCategoryItemByCategoryParentCodeData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    CategoryCodeParent?: string;
    CategoryCode?: string;
  };
  url: "/edu/v1/CategoryItem/get-category-item-by-category-parent-code";
};

export type GetEduV1CategoryItemGetCategoryItemByCategoryParentCodeResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1DistrictProvinceByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/District/province/{id}";
};

export type GetEduV1DistrictProvinceByIdResponses = {
  /**
   * OK
   */
  200: DistrictPaginatedResultReadable;
};

export type GetEduV1DistrictProvinceByIdResponse =
  GetEduV1DistrictProvinceByIdResponses[keyof GetEduV1DistrictProvinceByIdResponses];

export type GetEduV1DistrictByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/District/{id}";
};

export type GetEduV1DistrictByIdResponses = {
  /**
   * OK
   */
  200: DistrictPaginatedResultReadable;
};

export type GetEduV1DistrictByIdResponse =
  GetEduV1DistrictByIdResponses[keyof GetEduV1DistrictByIdResponses];

export type GetEduV1ExtInfoSettingData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    moduleCode?: string;
    searchKey?: string;
    pageSize?: number;
    pageNumber?: number;
  };
  url: "/edu/v1/ExtInfoSetting";
};

export type GetEduV1ExtInfoSettingResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1ExtInfoSettingData = {
  body?: AddExtInfoSettingCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/ExtInfoSetting";
};

export type PostEduV1ExtInfoSettingResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1ExtInfoSettingByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/ExtInfoSetting/{id}";
};

export type DeleteEduV1ExtInfoSettingByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1ExtInfoSettingByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/ExtInfoSetting/{id}";
};

export type GetEduV1ExtInfoSettingByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutEduV1ExtInfoSettingByIdData = {
  body?: UpdateExtInfoSettingCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/ExtInfoSetting/{id}";
};

export type PutEduV1ExtInfoSettingByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1MenuData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
    parentId?: number;
    pageNumber?: number;
    pageSize?: number;
  };
  url: "/edu/v1/Menu";
};

export type GetEduV1MenuResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1MenuData = {
  body?: CreateMenuCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Menu";
};

export type PostEduV1MenuResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1MenuResponse =
  PostEduV1MenuResponses[keyof PostEduV1MenuResponses];

export type GetEduV1MenuTreeData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    parentId?: number;
  };
  url: "/edu/v1/Menu/tree";
};

export type GetEduV1MenuTreeResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1MenuMenuUserData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Menu/menu-user";
};

export type GetEduV1MenuMenuUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1MenuMenuItemsData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    parentId?: number;
  };
  url: "/edu/v1/Menu/menu-items";
};

export type GetEduV1MenuMenuItemsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1MenuByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Menu/{id}";
};

export type DeleteEduV1MenuByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type DeleteEduV1MenuByIdResponse =
  DeleteEduV1MenuByIdResponses[keyof DeleteEduV1MenuByIdResponses];

export type GetEduV1MenuByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Menu/{id}";
};

export type GetEduV1MenuByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutEduV1MenuByIdData = {
  body?: EditMenuCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Menu/{id}";
};

export type PutEduV1MenuByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PutEduV1MenuByIdResponse =
  PutEduV1MenuByIdResponses[keyof PutEduV1MenuByIdResponses];

export type GetEduV1MenuPermissionGetByMenuByMenuIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    menuId: number;
  };
  query?: never;
  url: "/edu/v1/MenuPermission/get-by-menu/{menuId}";
};

export type GetEduV1MenuPermissionGetByMenuByMenuIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1MenuPermissionSetPermissionByMenuIdData = {
  body?: Array<MenuPermissionItemCommand>;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    menuId: number;
  };
  query?: never;
  url: "/edu/v1/MenuPermission/set-permission/{menuId}";
};

export type PostEduV1MenuPermissionSetPermissionByMenuIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1OrganizationData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    typeId?: number;
    searchKey?: string;
    pageSize?: number;
    pageNumber?: number;
  };
  url: "/edu/v1/Organization";
};

export type GetEduV1OrganizationResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1OrganizationData = {
  body?: AddOrganizationCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Organization";
};

export type PostEduV1OrganizationResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1OrganizationTreeData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Organization/tree";
};

export type GetEduV1OrganizationTreeResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1OrganizationByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Organization/{id}";
};

export type DeleteEduV1OrganizationByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1OrganizationByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Organization/{id}";
};

export type GetEduV1OrganizationByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutEduV1OrganizationByIdData = {
  body?: UpdateOrganizationCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Organization/{id}";
};

export type PutEduV1OrganizationByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1OrganizationOrganizationItemData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    organizationsId?: number;
  };
  url: "/edu/v1/Organization/organization-item";
};

export type GetEduV1OrganizationOrganizationItemResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1OrganizationGetItemsData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    idIgnore?: number;
  };
  url: "/edu/v1/Organization/get-items";
};

export type GetEduV1OrganizationGetItemsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1OrganizationUserOrganizationsByOrganizationIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    organizationId: number;
  };
  query?: {
    searchKey?: string;
    pageSize?: number;
    pageNumber?: number;
  };
  url: "/edu/v1/OrganizationUser/organizations/{organizationId}";
};

export type GetEduV1OrganizationUserOrganizationsByOrganizationIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1OrganizationUserByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/OrganizationUser/{id}";
};

export type DeleteEduV1OrganizationUserByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1OrganizationUserByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/OrganizationUser/{id}";
};

export type GetEduV1OrganizationUserByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1OrganizationUserOrganizationsByOrganizationIdUsersData = {
  body?: AssignUserToOrganizationCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    organizationId: number;
  };
  query?: never;
  url: "/edu/v1/OrganizationUser/organizations/{organizationId}/users";
};

export type PostEduV1OrganizationUserOrganizationsByOrganizationIdUsersResponses =
  {
    /**
     * OK
     */
    200: unknown;
  };

export type GetEduV1PartnerData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
    pageSize?: number;
    pageNumber?: number;
  };
  url: "/edu/v1/Partner";
};

export type GetEduV1PartnerResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1PartnerData = {
  body?: CreatePartnerCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Partner";
};

export type PostEduV1PartnerResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1PartnerByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Partner/{id}";
};

export type DeleteEduV1PartnerByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1PartnerByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Partner/{id}";
};

export type GetEduV1PartnerByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutEduV1PartnerByIdData = {
  body?: EditPartnerCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Partner/{id}";
};

export type PutEduV1PartnerByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1PartnerGetItemsData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Partner/get-items";
};

export type GetEduV1PartnerGetItemsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1PartnerGenerateAccessKeyByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Partner/generate-access-key/{id}";
};

export type GetEduV1PartnerGenerateAccessKeyByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1PartnerKeyData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
    partnerId?: number;
    pageSize?: number;
    pageNumber?: number;
  };
  url: "/edu/v1/PartnerKey";
};

export type GetEduV1PartnerKeyResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1PartnerKeyData = {
  body?: CreatePartnerAccessKeyCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/PartnerKey";
};

export type PostEduV1PartnerKeyResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1PartnerKeyByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/PartnerKey/{id}";
};

export type DeleteEduV1PartnerKeyByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1PartnerKeyByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/PartnerKey/{id}";
};

export type GetEduV1PartnerKeyByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutEduV1PartnerKeyByIdData = {
  body?: EditPartnerAccessKeyCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/PartnerKey/{id}";
};

export type PutEduV1PartnerKeyByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1PermissionData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
    pageNumber?: number;
    pageSize?: number;
  };
  url: "/edu/v1/Permission";
};

export type GetEduV1PermissionResponses = {
  /**
   * OK
   */
  200: PaginatedResultReadable;
};

export type GetEduV1PermissionResponse =
  GetEduV1PermissionResponses[keyof GetEduV1PermissionResponses];

export type PostEduV1PermissionData = {
  body?: CreatePermissionCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Permission";
};

export type PostEduV1PermissionResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1PermissionResponse =
  PostEduV1PermissionResponses[keyof PostEduV1PermissionResponses];

export type DeleteEduV1PermissionByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Permission/{id}";
};

export type DeleteEduV1PermissionByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type DeleteEduV1PermissionByIdResponse =
  DeleteEduV1PermissionByIdResponses[keyof DeleteEduV1PermissionByIdResponses];

export type GetEduV1PermissionByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Permission/{id}";
};

export type GetEduV1PermissionByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1PermissionByIdResponse =
  GetEduV1PermissionByIdResponses[keyof GetEduV1PermissionByIdResponses];

export type PutEduV1PermissionByIdData = {
  body?: EditPermissionCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Permission/{id}";
};

export type PutEduV1PermissionByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PutEduV1PermissionByIdResponse =
  PutEduV1PermissionByIdResponses[keyof PutEduV1PermissionByIdResponses];

export type PostEduV1PersonData = {
  body?: AddPersonCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Person";
};

export type PostEduV1PersonResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1PersonByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Person/{id}";
};

export type DeleteEduV1PersonByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutEduV1PersonByIdData = {
  body?: UpdatePersonCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Person/{id}";
};

export type PutEduV1PersonByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1PersonProfileData = {
  body?: AddPersonProfileCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/PersonProfile";
};

export type PostEduV1PersonProfileResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteEduV1PersonProfileByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/PersonProfile/{id}";
};

export type DeleteEduV1PersonProfileByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutEduV1PersonProfileByIdData = {
  body?: UpdatePersonProfileCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/PersonProfile/{id}";
};

export type PutEduV1PersonProfileByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1ProfileData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Profile";
};

export type GetEduV1ProfileResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1ProfileResponse =
  GetEduV1ProfileResponses[keyof GetEduV1ProfileResponses];

export type PutEduV1ProfileData = {
  body?: EditUserCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Profile";
};

export type PutEduV1ProfileResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostEduV1ProfileChangePasswordData = {
  body?: ChangePasswordUserCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Profile/change-password";
};

export type PostEduV1ProfileChangePasswordResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1ProvinceData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Province";
};

export type GetEduV1ProvinceResponses = {
  /**
   * OK
   */
  200: ProvincePaginatedResultReadable;
};

export type GetEduV1ProvinceResponse =
  GetEduV1ProvinceResponses[keyof GetEduV1ProvinceResponses];

export type GetEduV1RoleData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Role";
};

export type GetEduV1RoleResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1RoleResponse =
  GetEduV1RoleResponses[keyof GetEduV1RoleResponses];

export type PostEduV1RoleData = {
  body?: CreateRoleCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Role";
};

export type PostEduV1RoleResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1RoleResponse =
  PostEduV1RoleResponses[keyof PostEduV1RoleResponses];

export type DeleteEduV1RoleByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Role/{id}";
};

export type DeleteEduV1RoleByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type DeleteEduV1RoleByIdResponse =
  DeleteEduV1RoleByIdResponses[keyof DeleteEduV1RoleByIdResponses];

export type GetEduV1RoleByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Role/{id}";
};

export type GetEduV1RoleByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1RoleByIdResponse =
  GetEduV1RoleByIdResponses[keyof GetEduV1RoleByIdResponses];

export type PutEduV1RoleByIdData = {
  body?: EditRoleCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Role/{id}";
};

export type PutEduV1RoleByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PutEduV1RoleByIdResponse =
  PutEduV1RoleByIdResponses[keyof PutEduV1RoleByIdResponses];

export type GetEduV1RolePermissionData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    roleId?: number;
    searchKey?: string;
    pageNumber?: number;
    pageSize?: number;
  };
  url: "/edu/v1/RolePermission";
};

export type GetEduV1RolePermissionResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1RolePermissionResponse =
  GetEduV1RolePermissionResponses[keyof GetEduV1RolePermissionResponses];

export type PostEduV1RolePermissionSetData = {
  body?: SetRolePermissionCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/RolePermission/set";
};

export type PostEduV1RolePermissionSetResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1RolePermissionSetResponse =
  PostEduV1RolePermissionSetResponses[keyof PostEduV1RolePermissionSetResponses];

export type GetEduV1SemesterGetByAcademicYearByAcademicYearIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    academicYearId: number;
  };
  query?: never;
  url: "/edu/v1/Semester/get-by-academic-year/{academicYearId}";
};

export type GetEduV1SemesterGetByAcademicYearByAcademicYearIdResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type GetEduV1SemesterGetByAcademicYearByAcademicYearIdResponse =
  GetEduV1SemesterGetByAcademicYearByAcademicYearIdResponses[keyof GetEduV1SemesterGetByAcademicYearByAcademicYearIdResponses];

export type GetEduV1SemesterGetItemsData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Semester/get-items";
};

export type GetEduV1SemesterGetItemsResponses = {
  /**
   * OK
   */
  200: AcademicYearBaseResponse;
};

export type GetEduV1SemesterGetItemsResponse =
  GetEduV1SemesterGetItemsResponses[keyof GetEduV1SemesterGetItemsResponses];

export type PostEduV1SemesterData = {
  body?: CreateSemesterCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Semester";
};

export type PostEduV1SemesterResponses = {
  /**
   * OK
   */
  200: SemesterBaseResponse;
};

export type PostEduV1SemesterResponse =
  PostEduV1SemesterResponses[keyof PostEduV1SemesterResponses];

export type DeleteEduV1SemesterByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Semester/{id}";
};

export type DeleteEduV1SemesterByIdResponses = {
  /**
   * OK
   */
  200: SemesterBaseResponse;
};

export type DeleteEduV1SemesterByIdResponse =
  DeleteEduV1SemesterByIdResponses[keyof DeleteEduV1SemesterByIdResponses];

export type GetEduV1SemesterByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Semester/{id}";
};

export type GetEduV1SemesterByIdResponses = {
  /**
   * OK
   */
  200: SemesterBaseResponse;
};

export type GetEduV1SemesterByIdResponse =
  GetEduV1SemesterByIdResponses[keyof GetEduV1SemesterByIdResponses];

export type PutEduV1SemesterByIdData = {
  body?: UpdateSemesterCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Semester/{id}";
};

export type PutEduV1SemesterByIdResponses = {
  /**
   * OK
   */
  200: SemesterBaseResponse;
};

export type PutEduV1SemesterByIdResponse =
  PutEduV1SemesterByIdResponses[keyof PutEduV1SemesterByIdResponses];

export type GetEduV1SemesterGetCurrentData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/Semester/get-current";
};

export type GetEduV1SemesterGetCurrentResponses = {
  /**
   * OK
   */
  200: CurrentSemesterBaseResponse;
};

export type GetEduV1SemesterGetCurrentResponse =
  GetEduV1SemesterGetCurrentResponses[keyof GetEduV1SemesterGetCurrentResponses];

export type PostEduV1SemesterSetCurrentByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Semester/set-current/{id}";
};

export type PostEduV1SemesterSetCurrentByIdResponses = {
  /**
   * OK
   */
  200: CurrentSemesterBaseResponse;
};

export type PostEduV1SemesterSetCurrentByIdResponse =
  PostEduV1SemesterSetCurrentByIdResponses[keyof PostEduV1SemesterSetCurrentByIdResponses];

export type GetEduV1UserData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
    pageNumber?: number;
    pageSize?: number;
  };
  url: "/edu/v1/User";
};

export type GetEduV1UserResponses = {
  /**
   * OK
   */
  200: PaginatedResultReadable;
};

export type GetEduV1UserResponse =
  GetEduV1UserResponses[keyof GetEduV1UserResponses];

export type PostEduV1UserData = {
  body?: CreateUserCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/User";
};

export type PostEduV1UserResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1UserResponse =
  PostEduV1UserResponses[keyof PostEduV1UserResponses];

export type GetEduV1UserGetItemsData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
  };
  url: "/edu/v1/User/get-items";
};

export type GetEduV1UserGetItemsResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1UserGetItemsResponse =
  GetEduV1UserGetItemsResponses[keyof GetEduV1UserGetItemsResponses];

export type GetEduV1UserFindOneData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
  };
  url: "/edu/v1/User/find-one";
};

export type GetEduV1UserFindOneResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1UserFindOneResponse =
  GetEduV1UserFindOneResponses[keyof GetEduV1UserFindOneResponses];

export type DeleteEduV1UserByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/User/{id}";
};

export type DeleteEduV1UserByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type DeleteEduV1UserByIdResponse =
  DeleteEduV1UserByIdResponses[keyof DeleteEduV1UserByIdResponses];

export type GetEduV1UserByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/User/{id}";
};

export type GetEduV1UserByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type GetEduV1UserByIdResponse =
  GetEduV1UserByIdResponses[keyof GetEduV1UserByIdResponses];

export type PutEduV1UserByIdData = {
  body?: EditUserCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/User/{id}";
};

export type PutEduV1UserByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PutEduV1UserByIdResponse =
  PutEduV1UserByIdResponses[keyof PutEduV1UserByIdResponses];

export type PostEduV1AuthUserCheckMembershipData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    username?: string;
  };
  url: "/edu/v1/auth/User/check-membership";
};

export type PostEduV1AuthUserCheckMembershipResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1AuthUserCheckMembershipResponse =
  PostEduV1AuthUserCheckMembershipResponses[keyof PostEduV1AuthUserCheckMembershipResponses];

export type PostEduV1AuthUserNewMembershipData = {
  body?: NewUserMembershipCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/auth/User/new-membership";
};

export type PostEduV1AuthUserNewMembershipResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1AuthUserNewMembershipResponse =
  PostEduV1AuthUserNewMembershipResponses[keyof PostEduV1AuthUserNewMembershipResponses];

export type PostEduV1AuthUserTokenData = {
  body?: LoginUserCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/auth/User/token";
};

export type PostEduV1AuthUserTokenResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1AuthUserTokenResponse =
  PostEduV1AuthUserTokenResponses[keyof PostEduV1AuthUserTokenResponses];

export type PostEduV1AuthUserRefreshTokenData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    refreshToken?: string;
    accessToken?: string;
  };
  url: "/edu/v1/auth/User/refresh-token";
};

export type PostEduV1AuthUserRefreshTokenResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1AuthUserRefreshTokenResponse =
  PostEduV1AuthUserRefreshTokenResponses[keyof PostEduV1AuthUserRefreshTokenResponses];

export type PostEduV1AuthUserLogoutData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    refreshToken?: string;
  };
  url: "/edu/v1/auth/User/logout";
};

export type PostEduV1AuthUserLogoutResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1UserDeviceData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
    pageSize?: number;
    pageNumber?: number;
  };
  url: "/edu/v1/UserDevice";
};

export type GetEduV1UserDeviceResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1UserMembershipData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    userId?: number;
    searchKey?: string;
    pageNumber?: number;
    pageSize?: number;
  };
  url: "/edu/v1/UserMembership";
};

export type GetEduV1UserMembershipResponses = {
  /**
   * OK
   */
  200: PaginatedResultReadable;
};

export type GetEduV1UserMembershipResponse =
  GetEduV1UserMembershipResponses[keyof GetEduV1UserMembershipResponses];

export type PostEduV1UserMembershipData = {
  body?: CreateUserMembershipCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: never;
  url: "/edu/v1/UserMembership";
};

export type PostEduV1UserMembershipResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1UserMembershipResponse =
  PostEduV1UserMembershipResponses[keyof PostEduV1UserMembershipResponses];

export type PatchEduV1UserMembershipLockByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/UserMembership/lock/{id}";
};

export type PatchEduV1UserMembershipLockByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PatchEduV1UserMembershipLockByIdResponse =
  PatchEduV1UserMembershipLockByIdResponses[keyof PatchEduV1UserMembershipLockByIdResponses];

export type PatchEduV1UserMembershipUnlockByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/UserMembership/unlock/{id}";
};

export type PatchEduV1UserMembershipUnlockByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PatchEduV1UserMembershipUnlockByIdResponse =
  PatchEduV1UserMembershipUnlockByIdResponses[keyof PatchEduV1UserMembershipUnlockByIdResponses];

export type GetEduV1UserMembershipGetProfileUserMembershipsData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path?: never;
  query?: {
    searchKey?: string;
    pageNumber?: number;
    pageSize?: number;
  };
  url: "/edu/v1/UserMembership/get-profile-user-memberships";
};

export type GetEduV1UserMembershipGetProfileUserMembershipsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEduV1UserRoleGetByRoleByRoleIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    roleId: number;
  };
  query?: {
    searchKey?: string;
    pageNumber?: number;
    pageSize?: number;
  };
  url: "/edu/v1/UserRole/get-by-role/{roleId}";
};

export type GetEduV1UserRoleGetByRoleByRoleIdResponses = {
  /**
   * OK
   */
  200: PaginatedResultReadable;
};

export type GetEduV1UserRoleGetByRoleByRoleIdResponse =
  GetEduV1UserRoleGetByRoleByRoleIdResponses[keyof GetEduV1UserRoleGetByRoleByRoleIdResponses];

export type GetEduV1UserRoleGetByUserByUserIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    userId: number;
  };
  query?: {
    searchKey?: string;
    pageNumber?: number;
    pageSize?: number;
  };
  url: "/edu/v1/UserRole/get-by-user/{userId}";
};

export type GetEduV1UserRoleGetByUserByUserIdResponses = {
  /**
   * OK
   */
  200: PaginatedResultReadable;
};

export type GetEduV1UserRoleGetByUserByUserIdResponse =
  GetEduV1UserRoleGetByUserByUserIdResponses[keyof GetEduV1UserRoleGetByUserByUserIdResponses];

export type PostEduV1UserRoleUsersByUserIdRolesData = {
  body?: AssignRoleToUserCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    userId: number;
  };
  query?: never;
  url: "/edu/v1/UserRole/users/{userId}/roles";
};

export type PostEduV1UserRoleUsersByUserIdRolesResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1UserRoleUsersByUserIdRolesResponse =
  PostEduV1UserRoleUsersByUserIdRolesResponses[keyof PostEduV1UserRoleUsersByUserIdRolesResponses];

export type PostEduV1UserRoleRolesByRoleIdUsersData = {
  body?: AssignUserToRoleCommand;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    roleId: number;
  };
  query?: never;
  url: "/edu/v1/UserRole/roles/{roleId}/users";
};

export type PostEduV1UserRoleRolesByRoleIdUsersResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type PostEduV1UserRoleRolesByRoleIdUsersResponse =
  PostEduV1UserRoleRolesByRoleIdUsersResponses[keyof PostEduV1UserRoleRolesByRoleIdUsersResponses];

export type DeleteEduV1UserRoleByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/UserRole/{id}";
};

export type DeleteEduV1UserRoleByIdResponses = {
  /**
   * OK
   */
  200: BaseResponse;
};

export type DeleteEduV1UserRoleByIdResponse =
  DeleteEduV1UserRoleByIdResponses[keyof DeleteEduV1UserRoleByIdResponses];

export type GetEduV1WardDistrictByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Ward/district/{id}";
};

export type GetEduV1WardDistrictByIdResponses = {
  /**
   * OK
   */
  200: WardPaginatedResultReadable;
};

export type GetEduV1WardDistrictByIdResponse =
  GetEduV1WardDistrictByIdResponses[keyof GetEduV1WardDistrictByIdResponses];

export type GetEduV1WardByIdData = {
  body?: never;
  headers?: {
    "Accept-Language"?: "vi-VN" | "en-US";
  };
  path: {
    id: number;
  };
  query?: never;
  url: "/edu/v1/Ward/{id}";
};

export type GetEduV1WardByIdResponses = {
  /**
   * OK
   */
  200: WardPaginatedResultReadable;
};

export type GetEduV1WardByIdResponse =
  GetEduV1WardByIdResponses[keyof GetEduV1WardByIdResponses];

export type ClientOptions = {
  baseUrl: "https://localhost:7198" | (string & {});
};
